version: '3.9'

services:

  db:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - fastapi-net

  fastapi:
    build: .
    container_name: fastapi_app

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/postgres

    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

    networks:
      - fastapi-net

volumes:
  postgres:

networks:
  fastapi-net:
    driver: bridge